name: Claude Code Actions CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with ruff
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        ruff check --output-format=github .
        # Check formatting
        ruff format --check .
    
    - name: Test with pytest
      run: |
        pytest -v || echo "No tests found"
    
    - name: Test ranking viewer functionality
      run: |
        python swe_rank_viewer.py --format json > test_output.json
        python swe_rank_viewer.py --format summary
        echo "✅ Ranking viewer tests completed successfully"